const std = @import("std");
// INFO: try to not forget to update info in help command when changing operations
pub const OpType = enum {
    plus,
    minus,
    star,
    slash,
    percent,
    less,
    less_equal,
    greater,
    greater_equal,
    equal,
    not_equal,
    not,
    left_brace,
    right_brace,
    amp,
    amp_amp,
    bar,
    bar_bar,
    neg,
    abs,
    min,
    max,
    call,
    @"if",
    ifelse,
    dup,
    swap,
    drop,
    over,
    rot,
    clear,
    print,
    peek,
    stack,
    vars,
    varclear,
    quit,
    help,

    fn opToStr(self: OpType) []const u8 {
        return switch (self) {
            .plus => "+",
            .minus => "-",
            .star => "*",
            .slash => "/",
            .percent => "%",
            .less => "<",
            .less_equal => "<=",
            .greater => ">",
            .greater_equal => ">=",
            .equal => "==",
            .not_equal => "!=",
            .not => "!",
            .amp => "&",
            .amp_amp => "&&",
            .bar => "|",
            .bar_bar => "||",
            .dup => "dup",
            .swap => "swap",
            .drop => "drop",
            .over => "over",
            .rot => "rot",
            .neg => "neg",
            .abs => "abs",
            .min => "min",
            .max => "max",
            .call => "call",
            .@"if" => "if",
            .ifelse => "ifelse",
            .clear => "clear",
            .print => "print",
            .peek => "peek",
            .stack => "stack",
            .vars => "vars",
            .varclear => "varclear",
            .quit => "quit",
            .help => "help",
            .left_brace => "{",
            .right_brace => "}",
        };
    }

    pub fn isOpSymbol(self: OpType) bool {
        return switch (self) {
            .plus,
            .minus,
            .star,
            .slash,
            .percent,
            .less,
            .less_equal,
            .greater,
            .greater_equal,
            .equal,
            .not_equal,
            .not,
            .amp,
            .amp_amp,
            .bar,
            .bar_bar,
            .left_brace,
            .right_brace,
            => true,
            else => false,
        };
    }
};

pub const Token = union(enum) {
    int: i32,
    float: f64,
    bool: bool,
    op: OpType,
    set_var: []const u8,
    get_var: []const u8,

    pub fn format(self: Token, writer: *std.Io.Writer) std.Io.Writer.Error!void {
        switch (self) {
            .int => |i| try writer.print("{d}", .{i}),
            .float => |f| if (f == @floor(f)) try writer.print("{d:.1}", .{f}) else try writer.print("{d}", .{f}),
            .bool => |b| try writer.print("{}", .{b}),
            .op => |op| try writer.writeAll(op.opToStr()),
            .set_var => |v| try writer.print("${s}", .{v}),
            .get_var => |v| try writer.print("@{s}", .{v}),
        }
    }
};
